[package]
name = "pass-man"
version = "0.1.0"
edition = "2021"

[dependencies]
aes = "0.8.4"
base64 = "0.22.1"
dotenv = "0.15.0"
serde = { version = "1.0.204", features = ["derive"] }
sha3 = "0.10.8"
surrealdb = "1.5.4"
tokio = { version = "1.39.2", features = ["macros", "rt-multi-thread"] }
