[package]
name = "pass-man"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.204", features = ["derive"] }
surrealdb = "1.5.4"
tokio = { version = "1.39.2", features = ["macros", "rt-multi-thread"] }
